config/routes.rb
SportsBar::Application.routes.draw do

  root "locations#home"
  get "about" => "static#about"
  get "legal" => "static#legal"
  get "support" => "static#support"
  get ":city" => "locations#index", as: :city_slug
  get ":city/:name" => "locations#index", as: :location_slug
  
end

app/models/city.rb
class City < ActiveRecord::Base

  validates_presence_of :name, :slug, :variations, :state

  has_many :locations

end

app/models/location.rb
class Location < ActiveRecord::Base

  validates_presence_of :name

  has_many :flags
  has_many :images
  
  has_many :reviews
  has_many :users, through: :reviews

  has_many :location_teams
  has_many :teams, through: :location_teams

  belongs_to :city

end

app/models/location_team.rb
class LocationTeam < ActiveRecord::Base

  validates_presence_of :location_id, :team_id

  belongs_to :location
  belongs_to :team

end

app/models/model.rb
class Location < ActiveRecord::Base

  validates_presence_of :name

  has_many :flags
  has_many :images
  
  has_many :reviews
  has_many :users, through: :reviews

  has_many :location_teams
  has_many :teams, through: :location_teams

end

app/models/review.rb
class Review < ActiveRecord::Base

  validates_presence_of :location_id
  belongs_to :location

end

app/models/team.rb
class Team < ActiveRecord::Base

  validates_presence_of :name

  has_many :location_teams
  has_many :locations, through: :location_teams

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def home
    @locations = Location.order(:overall_rating).limit(10)
    @location = Location.order(:overall_rating).first

    render :index
  end

  # if param_city exists
  #   find city 
  # else
  #   redirect to Not Found

  # if param_name present
  #   find location
  #
  #   if location exists
  #     render view
  #   else
  #     redirect to Not Found
  #
  # else
  #   retrieve top-ranked location of city
  def index
    params[:city] || not_found
    @city = City.where("? = ANY (variations)", params[:city]).first || not_found
    redirect_to city_slug_path(city: @city.slug) if @city.slug != params[:city]

    @locations = Location.where(city: @city).order(:city_rating).limit(10)

    if params[:name].present?
      @location = Location.where(city: @city, name_slug: params[:name]).first || not_found
    else
      @location = Location.where(city: @city).order(:city_rating).first
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about

  end

  def home

  end

  def legal

  end

  def support

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
= render "shared/logo"

%nav.navbar.navbar-default{ role: "navigation" }
  .navbar-header
    %button.navbar-toggle{ type: "button", 'data-toggle' => "collapse", 'data-target' => ".navbar-ex1-collapse" }
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li
        = link_to "Home", root_path, title: "Home"
      %li
        = link_to "About", about_path, title: "About"
      %li
        = link_to "Support", support_path, title: "Support"
      %li
        = link_to "Terms", legal_path, title: "Terms"
      %li
        = link_to "Feedback", "#", title: "Feedback"
          
    %form.navbar-form.navbar-left{ role: "search" }
      .form-group
        %input.form-control{ type: "text", placeholder: "Search" }
      %button.btn.btn-default{ type: "submit" } Submit

app/views/layouts/_notices.html.haml
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    .alert{:class => "#{flash_class(level)}"}
      %a.close{ href: "#" }
        x
      = content_tag :p, flash[level]

app/views/layouts/application.html.haml
!!!
%html{ lang: "en" }
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Best Sports Bars"
    %meta{ content: "", name: "description" }
    %meta{ content: "", name: "keywords" }
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{ class: "#{params[:controller]} #{params[:action]}" }
    %header
      = render 'layouts/header'
    #content
      = render 'layouts/notices'
      = yield
    %footer
      = render 'layouts/footer'

app/views/locations/index.html.haml
.sidebar.col-xs-12.col-sm-5.col-md-4.col-lg-4
  = render "shared/sidebar", locations: @locations

.main.col-xs-12.col-sm-7.col-md-8.col-lg-8
  .row  
    .h1 
      - if params[:action] == "home"
        <em>##{@location.overall_rating}</em> #{@location.name}
      - else
        <em>##{@location.city_rating}</em> #{@location.name}

  .row
    .body
      .row
        .images.col-xs-12.col-sm-12.col-md-6.col-lg-6
          %img{ src: "http://placehold.it/300X200", alt: "#{@location.name}" }

        .info.col-xs-12.col-sm-12.col-md-6.col-lg-6
          .details
            Established: #{@location.year_founded}

          .address
            .street
              #{@location.address_1}
            .city-state
              #{@location.city.name}, #{@location.state} #{@location.zipcode}
            .website
              Site: #{link_to @location.website_url, @location.website_url, target: "_blank"}
            .email
              Email: #{mail_to "test@test.com", "test@test.com"}
              
      .row
        .ratings.col-xs-12.col-sm-12.col-md-6.col-lg-6
          %h2
            Ratings
          %table
            %tr
              %td.col-label
                Overall Rank
              %td
                = @location.overall_rating 
              %td.col-label
                City Rank
              %td
                = @location.city_rating 
            %tr
              %td.col-label
                Screen Rating
              %td
                4 
              %td.col-label
                Service Rating
              %td
                4 
            %tr
              %td.col-label
                Food Rating
              %td
                4 
              %td.col-label
                Drink Rating
              %td
                4 
            %tr
              %td.col-label
                Seating Rating
              %td
                4
              %td.col-label
                Some Other Rating
              %td
                4

        .amenities.col-xs-12.col-sm-12.col-md-6.col-lg-6
          %h2
            Amenities
          %table
            %tr
              %td
                Number of Screens
              %td
                15
              %td
                TV Provider
              %td
                DirecTV
            %tr
              %td
                HD TVs?
              %td
                Yes
              %td
                Has WiFi?
              %td
                Yes
            %tr
              %td
                Power Outlets?
              %td
                No
              %td
                Game Sound?
              %td
                Yes
            %tr
              %td
                Staff Colors?
              %td
                No
              %td
                Non-smoking?
              %td
                Yes
    .row
      .review.col-xs-12.col-sm-12.col-md-12.col-lg-12
        %h2
          Review
        %p
          Suspendisse potenti. Maecenas viverra tortor nec tempor cursus. Cras at mi in arcu congue ultricies vitae quis odio. Suspendisse nec vestibulum mauris. Donec tincidunt cursus accumsan. Maecenas fringilla elementum felis, eget adipiscing leo elementum non. Nunc quis quam eget urna sagittis placerat ut vitae massa.

app/views/shared/_logo.html.haml
- city = params[:city].present? ? params[:city] : "America"
%h1.logo
  The Best<br/>
  Sports Bars<br/>
  In <em>#{city}</em>

app/views/shared/_sidebar.html.haml
%ul{ class: "nav nav-pills nav-stacked" }
  - locations.each do |location|
    %li
      %span.rating
        - if params[:action] == "home"
          \##{location.overall_rating}
        - else
          \##{location.city_rating}
      %span.link
        = link_to location.name, location_slug_path(city: location.city.slug, name: location.name_slug), title: location.name